import { Compass, Globe2, Heart, MoveRight } from 'lucide-react'
import Button from '../components/Button'
import ScrollReveal from '../components/ScrollReveal'
import ServiceCard from '../components/ServiceCard'
import { services } from '../data/services'

export default function About() {
  return <main><section className="page-hero about-hero"><div className="container page-hero-content"><span className="eyebrow">Про МандриUA</span><h1>Ми допомагаємо світу<br /><em>стати ближчим</em></h1><p>Туристична агенція для тих, хто обирає не просто місце, а відчуття, з яким повернеться додому.</p></div></section><section className="section story"><div className="container story-grid"><div className="story-images"><img className="story-main" src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1100&q=80" alt="Мандрівники біля моря" /><img className="story-small" src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80" alt="Тропічний пляж" /></div><div className="story-copy"><span className="eyebrow">Наш підхід</span><h2>Подорожі з людським обличчям</h2><p>МандриUA — це простір для планування відпочинку, де важливі і великі мрії, і маленькі деталі. Ми уважно слухаємо, пропонуємо чесні варіанти та допомагаємо зібрати подорож, яка справді вам підходить.</p><p>Ми не вигадуємо універсальних сценаріїв. Комусь потрібна тиша біля моря, комусь — нові маршрути щодня, а комусь — час із найріднішими. У кожному випадку ми починаємо з розмови.</p><Button to="/contacts" variant="outline">Запланувати розмову <MoveRight size={17} /></Button></div></div></section><section className="section services-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Що ми робимо</span><h2>Послуги для вашого маршруту</h2></div><p>Від першого запиту до повернення додому — ми поруч на кожному етапі.</p></div><div className="services-grid">{services.map((service, index) => <ScrollReveal key={service.title} delay={index * 70}><ServiceCard service={service} /></ScrollReveal>)}</div></div></section><section className="about-strip"><div className="container about-strip-grid"><div><Compass size={26} /><strong>Ваш напрямок</strong><span>починається з діалогу</span></div><div><Globe2 size={26} /><strong>Світ</strong><span>має більше, ніж один маршрут</span></div><div><Heart size={26} /><strong>Враження</strong><span>залишаються назавжди</span></div></div></section></main>
}
